#!/bin/bash
set -eu

# shellcheck source=start-utils
. ${SCRIPTS:-/}start-utils

if ${REMOVE_OLD_MODS} == "TRUE"
then
  log "**********************************************************************"
  log "WARNING: Packwiz servers don't work with REMOVE_OLD_MODS=true."
  log "         Overriding to false."
  log "**********************************************************************"
fi
export REMOVE_OLD_MODS="FALSE"

# Download URL for pack.toml
requireVar PACKWIZ_MODPACK

export PACKWIZ_BOOTSTRAPPER_URL='https://github.com/comp500/packwiz-installer-bootstrap/releases/latest/download/packwiz-installer-bootstrap.jar'

wget -t3 -O 'packwiz-installer-bootstrap.jar' ${PACKWIZ_BOOTSTRAPPER_URL}
wget -t3 -O 'pack.toml' ${PACKWIZ_MODPACK}

java -jar packwiz-installer-bootstrap.jar -g -s server ${PACKWIZ_MODPACK}

if loader_ver=$(grep -oP '(?<=fabric = ").*(?=")' pack.toml)
then
  export TYPE=FABRIC
  exec ${SCRIPTS:-/}start-deployFabric "$@"
elif loader_ver=$(grep -oP '(?<=forge = ").*(?=")' pack.toml)
then
  export TYPE=FORGE
  exec ${SCRIPTS:-/}start-deployForge "$@"
else
  echo "Modloader identification from pack.toml was unsuccessful. Exiting."
  exit 2
fi
